PRODUCT_PACKAGES += \
    NotifDark-SystemUI-Gray \
    NotifDark-System-NotifDark-SystemUI-Gray \
    NotifDark-SystemUI-TransparentGray50 \
    NotifDark-System-NotifDark-SystemUI-TransparentGray50 \
    NotifDark-SystemUI-TransparentGray75 \
    NotifDark-System-NotifDark-SystemUI-TransparentGray75 \
    NotifDark-SystemUI-TransparentBlack50 \
    NotifDark-System-NotifDark-SystemUI-TransparentBlack50 \
    NotifDark-SystemUI-TransparentBlack75 \
    NotifDark-System-NotifDark-SystemUI-TransparentBlack75 \
    NotifLight-SystemUI-TransparentWhite \
    NotifLight-System-NotifLight-SystemUI-TransparentWhite \
    NotifLight-SystemUI-Gray \
    NotifLight-System-NotifLight-SystemUI-Gray \
    NotifLight-SystemUI-TransparentGray50 \
    NotifLight-System-NotifLight-SystemUI-TransparentGray50 \
    NotifLight-SystemUI-TransparentGray75 \
    NotifLight-System-NotifLight-SystemUI-TransparentGray75 \
    NotifLight-SystemUI-TransparentBlack50 \
    NotifLight-System-NotifLight-SystemUI-TransparentBlack50 \
    NotifLight-SystemUI-TransparentBlack75 \
    NotifLight-System-NotifLight-SystemUI-TransparentBlack75 \
